### 3. 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산

In [2]:
x = np.arange(1,101)
y = np.arange(1101, 1201)
z = x + y
z[:5] 

array([1102, 1104, 1106, 1108, 1110])

In [3]:
z = 3 *x
z[:5]

array([ 3,  6,  9, 12, 15])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [5]:
a > b

array([False, False,  True, False])

In [6]:
a / b

array([0.25, 1.  , 1.5 , 1.  ])

In [7]:
np.log(a), np.exp(a)

(array([0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [11]:
c = np.arange(6).reshape(2,3)
np.exp(c)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [12]:
c+3


array([[3, 4, 5],
       [6, 7, 8]])

- 차원 축소 연산

In [13]:
x = np.arange(1, 5)
np.sum(x)

10

In [14]:
x.sum()

10

In [16]:
x.min(), x.max(), x.mean()

(1, 4, 2.5)

In [18]:
# 대표값:
x.mean(), np.median(x)

(2.5, 2.5)

- all or any

In [20]:
np.all(np.array([True, False, True])) #모든 원소가 참인가?

False

In [22]:
np.any(np.array([True, False, True])) # 참인 원소가 하나라도 있는가?

True

- 2차원 이상의 연산

In [23]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# 모든 원소의 합, 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [40]:
# 행 방향으로 합/평군
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [41]:
# 열 방향으로 합 / 평균
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

- argmax, argmin

In [42]:
x = np.array([3,12,26,9,51,33])
np.argmax(x), np.argmin(x)

(4, 0)

In [39]:
y = x.reshape(2,3)
np.argmax(y, axis =0), np.argmin(y,axis =0)

(array([1, 1, 1], dtype=int64), array([0, 0, 0], dtype=int64))

- 연습문제

In [83]:
b = np.arange(1, 31).reshape(5,6).astype(float)
b

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [85]:
np.random.seed(2023)
np.set_printoptions(precision=4, suppress=True)
m = np.random.random(30).reshape(5,6)
m

array([[0.322 , 0.8904, 0.5881, 0.1266, 0.1413, 0.4679],
       [0.0221, 0.7273, 0.5244, 0.5449, 0.4564, 0.5014],
       [0.3945, 0.1512, 0.3609, 0.1621, 0.338 , 0.1803],
       [0.391 , 0.0356, 0.5649, 0.2035, 0.3206, 0.3766],
       [0.1841, 0.104 , 0.4549, 0.1959, 0.3785, 0.9305]])

In [100]:
# 전체의 최댓값
b.max(), np.round(np.max(m),4)

(30.0, 0.9305)

In [88]:
#각 행의 합
b.sum(axis=1), np.sum(m,axis=1)

(array([ 21.,  57.,  93., 129., 165.]),
 array([2.5363, 2.7764, 1.5869, 1.8921, 2.2479]))

In [94]:
# 각행의 최댓값
b.max(axis=1),   np.max(m, axis = 1)

(array([ 6., 12., 18., 24., 30.]),
 array([0.8904, 0.7273, 0.3945, 0.5649, 0.9305]))

In [96]:
# 각 열의 평균
b.mean(axis=0),  np.mean(m, axis=0)

(array([13., 14., 15., 16., 17., 18.]),
 array([0.2627, 0.3817, 0.4986, 0.2466, 0.327 , 0.4913]))

In [98]:
# 각 열의 최솟값
b.min(axis=0),   np.min(m, axis=0)

(array([1., 2., 3., 4., 5., 6.]),
 array([0.0221, 0.0356, 0.3609, 0.1266, 0.1413, 0.1803]))