### 1. Series

In [4]:
import numpy as np
import pandas as pd

- Series 생성
    - numpy 1차원 어레이 + index

In [5]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [6]:
type(s)

pandas.core.series.Series

In [7]:
# 인덱스를 별도로 설정하지 않으면, 인덱스는 0, 1, 2, ... 이 된다.
pd.Series(np.arange(10, 15))

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [10]:
s.index, type(s.index)

(Index(['서울', '부산', '인천', '대구'], dtype='object'),
 pandas.core.indexes.base.Index)

In [11]:
s.values, type(s.values)

(array([9904312, 3448737, 2890451, 2466052], dtype=int64), numpy.ndarray)

In [12]:
s.name = '인구'
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

- 연산(Operation)

In [13]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

- 인덱싱

In [23]:
s['부산'], s[1], s.부산             # 결과는 scalar

(3448737, 3448737, 3448737)

In [24]:
s['대구'], s[3], s[-1], s.대구

(2466052, 2466052, 2466052, 2466052)

In [16]:
s[[0, 1]]                   # 결과는 Series

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [17]:
s[['서울', '부산']]

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [19]:
s[(s > 2500000) & (s < 5000000)]    # 250만 초과 500만 미만

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [20]:
s[s > 5000000]

도시
서울    9904312
Name: 인구, dtype: int64

- 슬라이싱

In [21]:
# 숫자 인덱스로 하는 슬라이싱은 넘파이와 동일
s[:2]

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [22]:
# 인덱스 문자열로 하는 경우에는 : 뒤 인덱스를 포함
s['서울':'인천']

도시
서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64

- 시리즈와 딕셔너리

In [25]:
'서울' in s

True

In [26]:
for k, v in s.items():
    print(f'{k}: {v}')

서울: 9904312
부산: 3448737
인천: 2890451
대구: 2466052


In [27]:
d = {"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}
s2 = pd.Series(d)
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [28]:
# 순서를 정하고 싶으면, 인덱스를 별도로 설정해야 함
s2 = pd.Series(d, index=['서울','부산','인천','대전'])
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 인덱스 기반 연산

In [29]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [30]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [31]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [32]:
rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

- 데이터의 갱신, 삭제, 추가

In [35]:
rs['부산'] = 1.64
rs[1] = 2.83
rs.인천 = 9.82
rs

부산    1.64
서울    2.83
인천    9.82
dtype: float64

In [40]:
del rs['인천']      # rs.인천, rs[2] 는 사용할 수 없음
rs

부산    1.64
서울    2.83
dtype: float64

In [41]:
rs['광주'] = 1.51   # rs.인천, rs[2] 는 사용할 수 없음
rs

부산    1.64
서울    2.83
광주    1.51
dtype: float64

- 연습 문제 4.1.1

In [47]:
ser1 = pd.Series(np.arange(11,15), index='a b c d'.split())
ser2 = pd.Series(np.arange(38,45,2), index='a b c x'.split())
print(ser1, ser2, sep='\n')

a    11
b    12
c    13
d    14
dtype: int32
a    38
b    40
c    42
x    44
dtype: int32


In [48]:
print(ser1 + ser2, ser1 - ser2, ser1 * ser2, ser1 / ser2, sep='\n')

a    49.0
b    52.0
c    55.0
d     NaN
x     NaN
dtype: float64
a   -27.0
b   -28.0
c   -29.0
d     NaN
x     NaN
dtype: float64
a    418.0
b    480.0
c    546.0
d      NaN
x      NaN
dtype: float64
a    0.289474
b    0.300000
c    0.309524
d         NaN
x         NaN
dtype: float64


- 중요한 method

In [49]:
dice = pd.Series(np.random.randint(1, 7, 10))
dice

0    4
1    2
2    6
3    2
4    1
5    5
6    2
7    5
8    3
9    3
dtype: int32

In [50]:
# element의 갯수
dice.count()

10

In [51]:
# 고유한 값
dice.unique()

array([4, 2, 6, 1, 5, 3])

In [52]:
# 고유한 값의 갯수
dice.nunique()

6

In [53]:
# 고유한 값 별로 갯수
dice.value_counts() 

2    3
5    2
3    2
4    1
6    1
1    1
Name: count, dtype: int64

In [54]:
np.unique(dice.values, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([1, 3, 2, 1, 2, 1], dtype=int64))

In [55]:
dice.min(), dice.max(), dice.sum(), dice.mean()

(1, 6, 33, 3.3)

In [56]:
# 요약 기술통계
dice.describe()

count    10.000000
mean      3.300000
std       1.636392
min       1.000000
25%       2.000000
50%       3.000000
75%       4.750000
max       6.000000
dtype: float64

In [57]:
# sort
dice.sort_values()

4    1
1    2
3    2
6    2
8    3
9    3
0    4
5    5
7    5
2    6
dtype: int32

In [58]:
# 데이터 기준 오름차순
s.sort_values()

도시
대구    2466052
인천    2890451
부산    3448737
서울    9904312
Name: 인구, dtype: int64

In [59]:
# 데이터 기준 내림차순
s.sort_values(ascending=False)

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [60]:
# 인덱스 기준 오름차순
s.sort_index()

도시
대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 인구, dtype: int64

In [61]:
# 인덱스 기준 내림차순
s.sort_index(ascending=False)

도시
인천    2890451
서울    9904312
부산    3448737
대구    2466052
Name: 인구, dtype: int64

In [62]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [63]:
# inplace 옵션을 True로 하면 자기파괴적 메소드가 됨
s.sort_index(inplace=True)
s

도시
대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 인구, dtype: int64

- 결측치(Na, NaN, Null) 처리

In [64]:
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [65]:
ds.isna()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [66]:
ds.isnull()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [67]:
# 0이 아닌 값이 나오면 데이터 안에 결측치가 있음
ds.isna().sum()

2

In [68]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class   
0         0       3    male  22.0      1      0   7.2500        S  Third  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [69]:
survived = titanic['survived']
age = titanic['age']

In [70]:
survived.isna().sum()       # 결측치가 없음

0

In [72]:
age.isna().sum()            # 결측치가 177개 있음

177

In [74]:
survived.count()            # 결측치를 제외한 데이터 갯수

891

In [78]:
# 결측치를 제거
ds.dropna(inplace=True)
ds

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [80]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [81]:
# 결측치를 중앙값으로 대체
ds.fillna(ds.median())

대구    258416.0
대전    258416.0
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [82]:
# 결측치를 평균값으로 대체하고 ds를 변경
ds.fillna(ds.mean(), inplace=True)
ds

대구    195597.333333
대전    195597.333333
부산     55546.000000
서울    272830.000000
인천    258416.000000
dtype: float64

In [83]:
# 결측치를 0으로 설정하고, 데이터 타입을 정수형으로 변경
ds = s - s2
ds = ds.fillna(0).astype(int)
ds

대구         0
대전         0
부산     55546
서울    272830
인천    258416
dtype: int32