### 1. Numpy N-Dimensional Array

In [42]:
import numpy as np

- ndarray와 list의 차이

In [43]:
l = [1,2,3,4,5]
l = [i*i for i in l]
l

[1, 4, 9, 16, 25]

In [44]:
n = np.array([1,2,3,4,5], dtype=int)
n

array([1, 2, 3, 4, 5])

In [45]:
n = np.square(n)
n

array([ 1,  4,  9, 16, 25])

- 1차원 배열(Vector) 만들기

In [46]:
a = np.array((1,2,3,4,5,6,7,8,9,10))
type(a)

numpy.ndarray

In [47]:
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (10,), 1, 10)

In [48]:
# 벡터화 연산
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
a = np.array([1,2,3])
b = np.array([10,20,30])
c = 2* a + b
c

array([12, 24, 36])

In [50]:
a==2, b>10

(array([False,  True, False]), array([False,  True,  True]))

- 2차원  배열(Matrix)

In [51]:
c = np.array([[1,2,3], [4,5,6]]) # np.arange(1,7).reshape(2, 3)
print(c)

[[1 2 3]
 [4 5 6]]


In [52]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [54]:
t = np.arange(1,25).reshape(2,3,4)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [56]:
t.dtype, t.shape, t.ndim, t.size

(dtype('int32'), (2, 3, 4), 3, 24)

- 배열의 인덱싱

In [57]:
a

array([1, 2, 3])

In [58]:
a[0], a[1], a[2], a[-1]

(1, 2, 3, 3)

In [59]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
c[0,0], c[-1,0],c[1,2]

(1, 4, 6)

- 배열의 슬라이싱

In [62]:
l =[[1,2,3],[4,5,6,],[7,8,9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [65]:
# 리스트에서는 행과 열로 동시에 슬라이싱이 안된다.
l[:2][1:]

[[4, 5, 6]]

In [66]:
c = np.arange(1, 10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# 위에 두 행
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
# 오른쪽 두열
c[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [74]:
c[:-1,::2]

array([[1, 3],
       [4, 6]])

In [76]:
c[::2,::2]

array([[1, 3],
       [7, 9]])

In [98]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [99]:
m[1,2]

7

In [100]:
m[2,-1]

14

In [101]:
m[1,1:3]

array([6, 7])

In [102]:
m[1:,2]

array([ 7, 12])

In [90]:
m[0:2,3:]

array([[3, 4],
       [8, 9]])

- 배열 인덱싱(Fancy indexing)

In [104]:
# idx 값이 True/False 이면 True 값이 있는 곳의 원소가 추출된다(Filter).
a = np.array([1,2,3,4,5,6,7,8,9,10])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([1, 3, 5, 7, 9])

In [105]:
a % 2 ==1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [106]:
a[a % 2==1]

array([1, 3, 5, 7, 9])

In [108]:
# idx 값이 정수값(인덱스)이면 해당 인덱스의 원소가 선택된다.
idx = np.array([1, 3, 5, 7, 9])
a[idx]

array([ 2,  4,  6,  8, 10])

In [109]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [110]:
x[x % 3 ==0]

array([ 3,  6,  9, 12, 15, 18])

In [112]:
x[x % 4 ==1]

array([ 1,  5,  9, 13, 17])

In [124]:
 x[(x % 4 ==1) & (x % 3 ==0)]


array([9])

In [125]:
# 위에서 구한 결과값은 ndarray 이고, 원소의 벨류값을 끄집어 내려면 다시 인덱싱을 해주어야 한다.
x[8], x[(x % 4 ==1) & (x % 3 ==0)][0]

(9, 9)