- 난수 발생과 카운팅

In [1]:
import numpy as np

- seed 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

-데이터의 순서 바꾸기

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터 셈플링

In [13]:
np.random.choice(5,5, replace = False)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

In [14]:
x = np.random.randint(1, 100, 10)

In [16]:
x

array([64, 49, 33, 30, 50, 50, 50, 50, 54, 39])

In [17]:
np.random.choice(x, 5, replace=False)

array([50, 30, 33, 49, 39])

In [18]:
np.random.random(10)

array([0.40615836, 0.62311131, 0.80221535, 0.09702613, 0.81625998,
       0.02808046, 0.01545164, 0.56690572, 0.59310305, 0.9147945 ])

In [20]:
# randint(low, high, N) - [low,  high]
np.random.randint(1,7,10)

array([2, 6, 3, 4, 6, 2, 4, 5, 4, 6])

In [23]:
# normalr(평균, 표준편차, N)
np.random.normal(170,10,10)

array([167.811719  , 156.27033373, 179.41739428, 174.08110255,
       167.98052652, 191.50613657, 164.40371641, 186.194802  ,
       164.55017513, 165.36456357])

In [26]:
# rand(N) = 표주정규분포 N(0,1)
np.random.randn(10)

array([-2.10846967,  1.92129592,  0.83141425, -1.13348183, -2.33197703,
       -0.50921416, -1.34637198,  0.90006549, -0.46832917, -0.22907534])

In [28]:
# binomial(시도횟수, 평균, N) 이항 분포 B(N,P)
np.random.binomial(10,0.5,20).reshape(4,5)

array([[5, 7, 7, 4, 5],
       [4, 6, 3, 2, 5],
       [5, 6, 5, 3, 6],
       [5, 4, 4, 5, 6]])

In [29]:
# 가설 검정 : t- 검정
# standard_t(자유도, N)
np.random.standard_t(2,10)

array([ 1.06564951e-02, -2.93716128e+00,  3.76818931e-01,  2.01689465e+00,
        1.46715762e+00, -8.61493429e-01,  6.61391681e+00,  1.49806598e+01,
        5.57285602e-01,  7.03757618e-01])

- 연습문제 3.5.1

In [32]:
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
np.random.binomial(1,0.5,10)

array([1, 1, 1, 0, 0, 0, 1, 0, 1, 0])

In [78]:
#주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
np.random.randint(1,7,100).mean()

3.31

- 연습문제 3.5.2

In [138]:
num = 10000
b = np.random.normal(0,0.01,5)
for i in range(5):
    num = num*(1+ b[i])
    num = int(np.round(num))
    print(num,end=' ')

9857 9737 9955 9953 10043 

In [140]:
# list로 해결
np.random.seed(2023)
rate = np.random.normal(0,0.01,250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [151]:
# 1. list로 해결
price = 10000
price_list = []
for i in range(250):
    price = price*(1+ rate[i])
    price = int(np.round(price))
    price_list.append(price)
price_array = np.array(price_list)
price_array[-10:]

array([[1.06564951e-02, 2.93716128e+00, 3.76818931e-01, 2.01689465e+00,
        1.46715762e+00],
       [8.61493429e-01, 6.61391681e+00, 1.49806598e+01, 5.57285602e-01,
        7.03757618e-01]])

In [157]:
# 2. array로 해결
price_array2 = np.zeros(250, dtype = int)
price = 10000
for i in range(250):
    price = price*(1+ rate[i])
    price = int(np.round(price))
    price_array2[i] = price
price_array2[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [165]:
dices = np.random.randint(1,7,100)
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [167]:
indices, count = np.unique(dices, return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([12, 17, 13, 14, 24, 20], dtype=int64))

In [178]:
np.sum(indices * count) / np.sum(count)

3.81

In [180]:
np.mean(dices)

3.81

In [182]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [183]:
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [184]:
np.bincount(dices, minlength = 6)

array([ 0, 12, 17, 13, 14, 24, 20], dtype=int64)